name: Generate Release Keystore
on: workflow_dispatch
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -storetype PKCS12 \
            -keystore subtitletranslator-release.jks \
            -alias subtitletranslator \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass 'COAOeTJthXCs8RN3UMSNZiFFSW7R' \
            -keypass 'COAOeTJthXCs8RN3UMSNZiFFSW7R' \
            -dname "CN=Leno, OU=Development, O=SubtitleTranslator, L=Riyadh, ST=Riyadh, C=SA"
      - name: Upload as Release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: keystore-temp-${{ github.run_id }}
          name: "Temporary Keystore Download"
          files: subtitletranslator-release.jks
          draft: false
          prerelease: true
