name: Generate Release Keystore
on: workflow_dispatch
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -storetype PKCS12 \
            -keystore subtitletranslator-release.jks \
            -alias subtitletranslator \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass 'COAOeTJthXCs8RN3UMSNZiFFSW7R' \
            -keypass 'COAOeTJthXCs8RN3UMSNZiFFSW7R' \
            -dname "CN=Leno, OU=Development, O=SubtitleTranslator, L=Riyadh, ST=Riyadh, C=SA"
      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: subtitletranslator-release-keystore
          path: subtitletranslator-release.jks
          retention-days: 1
